---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by suho.
--- DateTime: 2022-09-19 오후 7:25
---
local res = require("s1/_2")
print("Shared/_1 loaded")
local t = 1;
return {
    t
};