---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by suho.
--- DateTime: 2022-09-20 오후 11:18
---

print("test2.lua logging")

return function(...)
    print("test2.function called")
end